### ISSUE TITLE
Plots no longer working in current R version

### ISSUE THREAD

**Issue by thibautjombart** [Hackout3/epicontacts#122]
Plots no longer display on the current version of R on my computer:
```
library(outbreaks)
library(epicontacts)
x <- make_epicontacts(linelist = mers_korea_2015$linelist,
                      contacts = mers_korea_2015$contacts, 
                      directed = TRUE)
x
plot(x)
```
Gets me the blank page below:
![image](https://user-images.githubusercontent.com/10757154/137281575-2ee69192-13a6-4a5b-960b-a3d0e379c341.png)

If this can be replicated, this is a major bug which should be fixed asap.

**Comment by thibautjombart** [comment]
I think I found it. The column node$group.color seems to no longer be used and causes the problem. nodes$color replaces it, but the color for shapes with fontawesome still needs to be set when using shapes. I will post a PR later today after going through tests.

**Comment by finlaycampbell** [comment]
Thanks for looking into this - let me know if there's any I can help with!
