### ISSUE TITLE
Release version 1.1.2

### ISSUE THREAD

**Issue by thibautjombart** [Hackout3/epicontacts#124]
@vpnagraj it would be great if we could release epicontacts 1.1.2 on CRAN in the coming days, since version 1.1.2 fixes a major bug currently caused by the latest version of visNetwork (see https://github.com/reconhub/epicontacts/issues/122). I will be using epicontacts for a short course running 22-26 Nov, but it is also used quite widely now :)

**Comment by thibautjombart** [comment]
Thanks @vpnagraj  this is awesome. Apologies for the confusion, I initially thought @finlaycampbell was maintainer, then thought I was wrong and it was you, and now the fact that roles had been switched some time ago kind of rings a bell. I suspect CRAN will take this submission as the first change of maintainer. Since you got that release ready, would you like to submit from this last time, cc-ing @finlaycampbell and explaining the change of maintainer? Would that be okay?

**Comment by finlaycampbell** [comment]
@vpnagraj - if you could re-submit, I can then confirm the submission!

**Comment by vpnagraj** [comment]
aha! ok just re-built and submitted again. let me know when you get the confirmation email

**Comment by finlaycampbell** [comment]
Just confirmed the submission - let's hope it goes through without any issues!

**Comment by finlaycampbell** [comment]
It needs confirmation from the old maintainer address - hope you' received an email @vpnagraj!
